config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  resources :list_positions, only: :show
  resources :positions, only: :index

  resources :fpl_teams, except: [:new, :create, :destroy] do
    resources :fpl_team_lists, only: [:index, :show, :update] do
      resources :waiver_picks, only: [:create, :update, :destroy]
    end
    resources :waiver_picks, only: :index
    resources :inter_team_trade_groups, only: [:index, :create, :update, :destroy]
    resources :trades, only: :create
  end

  resources :leagues, except: [:index, :destroy] do
    resources :draft_picks, only: [:index, :create, :update]
    resources :mini_draft_picks, only: [:index, :create]
    resources :pass_mini_draft_picks, only: :create
  end

  resources :current_rounds, only: :index

  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'
  mount Sidekiq::Web => '/sidekiq'

  get '/join-a-league', to: 'join_leagues#new', path: 'join-a-league'
  post '/join-a-league', to: 'join_leagues#create', as: 'join_leagues'

  root to: 'rounds#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  resources :rounds, only: [:show, :index]

  resources :players, only: [:show, :index]

  resources :teams, only: [:index, :show]

  match "*path", to: "errors#show", via: :all
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title FplApp
    = favicon_link_tag 'soccer-ball'
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true)
    = javascript_include_tag('application', 'data-turbolinks-track' => true)
    = action_cable_meta_tag
    meta http-equiv="Content-Language" content="en"
    = csrf_meta_tags
    javascript:
      window.fplVars = {};
    = yield :inline_javascript_vars

  body class="controller-#{params[:controller].gsub('_', '-')} action-#{params[:action].gsub('_', '-')}"
    nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed aria-expanded='false' data-target='#nav' data-toggle='collapse' type='button'
            span.sr-only
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href='/'  FplApp
        #nav.collapse.navbar-collapse
          ul.nav.navbar-nav.navbar-left
            li = link_to('Players', players_path)
            li = link_to('Teams', team_path(Team.order(:position).first))
          ul.nav.navbar-nav.navbar-right
            - if current_user
              - if current_user.fpl_teams.any?
                li = link_to('My Fpl Teams', fpl_teams_path)
              li = link_to('Create a League', new_league_path)
              li = link_to('Join a League', join_a_league_path)
            li = sign_up_link
            li = session_link

    .container-fluid
      - flash.each do |key, value|
        - if value
          div class="alert alert-#{key} alert-dismissable"
            button type='button' data-dismiss='alert' class='close'
              span aria-hidden='true' &times;
            = value

    = yield
    #root
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'